title: Delta Green
description: My Delta Green campaign
theme: just-the-docs

color_scheme: dark

url: https://benjamenhogben.github.io/deltagreen

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/benjamenhogben/deltagreen
